### ISSUE TITLE
Problem with bootstrap progressbar

### ISSUE THREAD

**Issue by itsmh** [mortezakarimi/yii2-gentelella-rtl#1]
Hi and thanks for the good work,

there are some problem loading bootstrap's progress bar assets, I see that the `vendors` dir was removed in the [main repo](https://github.com/mortezakarimi/gentelella-rtl) and I'm not sure there's a build to fix it or not or the RTL package of bootstrap may contain that bootstrap progress bar already. if its the case maybe removing 
https://github.com/mortezakarimi/yii2-gentelella-rtl/blob/ffa0aa724cbd9afff61bea80bcae74290b8d426f/assets/BootstrapProgressbar.php#L14
will do the work.

any suggestions or solutions are appreciated

**Comment by mortezakarimi** [comment]
Hi
In the [main repo production vendors](https://github.com/mortezakarimi/gentelella-rtl/tree/gh-pages/vendors) bootstrap's progress bar assets exists and when you install package via composer everything will be okey
last changes and fixes will be released and many bugs fixed
