### ISSUE TITLE
persian datepicker problem

### ISSUE THREAD

**Issue by itsmh** [mortezakarimi/yii2-gentelella-rtl#3]
Hi,
There was a problem loading assets while trying to add datepicker widget
`<?= PersianDatePicker::widget(['attribute'=>'start_date', 'model'=> $model])?>`
`namespaces` were wrong while they were loading I've created a [pull request](https://github.com/mortezakarimi/yii2-gentelella-rtl/pull/2) for it.

**Comment by mortezakarimi** [comment]
Thanks for your contributing
